<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<Configurations>Debug;Release</Configurations>

		<!--The file where mod information which is required for publishing mod on PDX mods are stored-->
		<PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
	</PropertyGroup>

	<!--Imports must be after PropertyGroup block-->
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />

	<ItemGroup>
		<Reference Update="System">
			<Private>False</Private>
		</Reference>
		<Reference Update="System.Core">
			<Private>False</Private>
		</Reference>
		<Reference Update="System.Data">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Include="$(ModPropsFile)" Link="Properties\Mod.props" />
		<None Include="$(ModTargetsFile)" Link="Properties\Mod.targets" />
	</ItemGroup>
	<ItemGroup>
		<Content Include=".BuildContent\IncludedAssets\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include=".BuildContent\Images\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="ctrlC_thumbnails\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Colossal.AssetPipeline">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.AssetPipeline.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.Core">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.Core.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.IO">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.IO.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.IO.AssetDatabase">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.IO.AssetDatabase.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.Localization">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.Localization.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.Logging">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.Logging.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.Mathematics">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.Mathematics.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.PSI.Common">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.PSI.Common.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.UI">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.UI.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Colossal.UI.Binding">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Colossal.UI.Binding.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Game">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Game.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Burst">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Unity.Burst.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Collections">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Unity.Collections.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Entities">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Unity.Entities.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.InputSystem">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Unity.InputSystem.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Mathematics">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\Unity.Mathematics.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ImageConversionModule">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.JSONSerializeModule">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestModule">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestWWWModule">
	    <HintPath>D:\Spel\Cities- Skylines II - PC Edition\Content\Cities2_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<Target Name="BuildUI" AfterTargets="AfterBuild">
		<Exec Command="npm run build" WorkingDirectory="$(ProjectDir)/ctrlC-UI" />
	</Target>

	<ItemGroup>
	  <Reference Update="System.Drawing">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.IO.Compression.FileSystem">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.Numerics">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.Runtime.Serialization">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.Xml">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.Xml.Linq">
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ctrlC-UI\src\thumbnails\" />
	</ItemGroup>

</Project>
